# Blue Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      version: blue
  template:
    metadata:
      labels:
        app: hello
        version: blue
    spec:
      containers:
      - name: hello
        image: hashicorp/http-echo
        args:
          - "-text=Hello from BLUE"
---
# Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
    version: blue
  ports:
  - port: 80
    targetPort: 5678